name: Script - npm run db:populate
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Application environment to execute in.
        required: true
      term:
        description: Academic term to execute descript with. ie 202009, 202001
        required: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress
      - name: Lint
        run: npm run lint
  npm-run:
    name: Execute Script
    needs: [ lint ]
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ./functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Execute Script
        run: npm run db:populate ${{ github.event.inputs.term }}
        
