name: Script - upserts course information to Algolia
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Application environment to execute in.
        required: true
      term:
        description: Academic term to execute the script with. ie 202009, 202001
        required: true
jobs:
  update-algolia:
    name: Update Algolia index
    needs: [lint]
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ./functions
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress
      - name: Run Update Algolia Script
        run: npx ts-node ./scripts/update-algolia-index.ts ${{ github.event.inputs.term }}
